scalar Date

type RoomConnection {
  totalCount: Int!
  edges: [RoomEdge]!
  pageInfo: PageInfo!
}

type RoomEdge {
  node: Room!
  cursor: String!
}

type PageInfo {
  hasPreviousPage: Boolean!
  hasNextPage: Boolean!
  startCursor: String
  endCursor: String
}

enum RoomType {
  PRACTICE_ROOM
  CONCERT_HALL
  ADMINISTRATIVE_SPACE
  CLASSROOM
  STUDIO
  LIBRARY
  MEETING_ROOM
  THEATER
}

type Room {
  id: ID!
  venue: Venue!
  code: String!
  type: RoomType!
  size: Int!
  equipment: [Equipment]
  pictureUrl: String
  isBookable: Boolean!
  department: Department
  isFree: Boolean
  description: String!
}

type Query {
  findRoom(roomId: ID!): Room
  rooms(
    startsAt: Date
    endsAt: Date
    venueIds: [ID!]
    roomTypes: [RoomType!]
    equipmentIds: [ID!]
    isBookable: Boolean
    searchKeyword: String
    after: String
    first: Int
  ): RoomConnection!
}

type Mutation {
  setRoomBookableStatus(roomId: ID!, isBookable: Boolean!): Room!
  createRoom(
    venueId: ID!
    code: String!
    type: RoomType!
    size: Int!
    equipmentIds: [ID!]!
    pictureUrl: String
    isBookable: Boolean!
    departmentId: ID!
  ): Room!

  updateRoom(
    roomId: ID!
    code: String
    type: RoomType
    size: Int
    equipmentIds: [ID!]
    pictureUrl: String
    isBookable: Boolean
    departmentId: ID
  ): Room!
  deleteRoom(roomId: ID!): Boolean!
  addEquipmentToRoom(roomId: ID!, equipmentIds: [ID!]!): Room!
  removeEquipmentFromRoom(roomId: ID!, equipmentIds: [ID!]!): Room!
}
