export const EquipmentTypes = [
  'Piano',
  'Music stands',
  'Chairs',
  'Whiteboard',
  'Projector',
  'AV system',
  'Sheet music storage',
  'Mirrors',
  'Screen',
  'Soundproofing panels',
  'Digital keyboard',
  'Guitar amps',
  'Instrument storage lockers',
  'Drum kit',
  'Recording equipment',
  'Speakers',
  'Conductor\'s podium',
  'Timpani',
  'Lighting equipment',
  'Harpsichord',
  'Tuning devices',
  'Music technology setup',
  'Dance bars',
  'Upright bass stands',
  'Video recording equipment',
  'Monitors',
  'Metronomes',
  'Electronic metronomes',
  'Acoustic panels',
  'Practice pads',
];

