enum UserRole {
  ADMIN
  STUDENT
  TEACHER
  MANAGER
}

enum UserStatus {
  ACTIVE
  PENDING
  DISABLED
}

type User {
  id: ID!
  givenName: String!
  middleName: String
  familyName: String!
  username: String!
  email: String!
  role: UserRole!
  status: UserStatus!
  department: Department!
  userNumber: Int!
}

input UserInput {
  givenName: String!
  middleName: String
  familyName: String!
  email: String!
  role: UserRole!
  status: UserStatus!
  departmentId: ID!
}

enum TokenType {
  ACTIVATION
  PASSWORD_RESET
}

type AccessToken {
  value: String!
}

type ActivationToken {
  token: String!
  expires_at: Date!
  used: Boolean!
}

type Query {
  allUsers: [User!]!
  findUser(id: ID!): User
  findUserByName(name: String!): User
  findUsersByRole(role: UserRole!): [User!]!
  findUsersByDepartment(departmentId: ID!): [User!]!
  currentUser: User
  checkActivationToken(activationToken: String!): Boolean!
  testQuery: String!
}

type UserResponse {
  success: Boolean!
  message: String!
  id: ID
}

type Mutation {
  createUser(userInput: UserInput!): User

  bulkCreateUsers(users: [UserInput!]!): [User]

  authenticate(username: String!, password: String!): AccessToken

  updateUser(
    userId: ID!
    givenName: String
    familyName: String
    middleName: String
    username: String
    email: String
    password: String
  ): User

  activateUser(activationToken: String!, newPassword: String!): UserResponse!

  deleteUser(userId: ID!): UserResponse!
  updateUserStatus(userId: ID!, status: UserStatus!): User
  resetPassword(
    token: String!
    oldPassword: String!
    newPassword: String!
  ): UserResponse!
  changePassword(oldPassword: String!, newPassword: String!): UserResponse!
  requestPasswordReset(email: String!): UserResponse!

  signupRequest(userInput: UserInput!): UserResponse!
}
