export const Departments = [
  'Department of Piano',
  'Department of Organ and Harpsichord',
  'Violin Department under Professor E. D. Grach',
  'Violin Department under Professor V. M. Ivanov',
  'Violin Department under Professor S. I. Kravchenko',
  'Department of Viola',
  'Department of Cello and Double Bass',
  'Harp Class',
  'Department of Woodwind Instruments',
  'Department of Brass and Percussion Instruments',
  'Department of Opera Training',
  'Department of Solo Singing',
  'Department of Contemporary Music',
  'Department of Interdisciplinary Specializations for Musicologists',
  'Department of Foreign Music History',
  'Department of Composition',
  'Department of Russian Music History',
  'Department of Music Theory',
  'Department of Keyboard Instruments',
  'Department of String, Wind, and Percussion Instruments',
  'Department of Opera and Symphony Conducting',
  'Department of Choral Conducting',
  'Department of History and Theory of Performing Arts',
  'Department of Accompaniment Art',
  'Interfaculty Department of Chamber Ensemble and Quartet',
  'Interfaculty Department of Piano',
  'Department of Humanities',
  'Interfaculty Department of Foreign Languages, European Languages Section',
  'Interfaculty Department of Foreign Languages, Russian Language Section',
  'Interfaculty Department of Musical Information Technology',
  'Interfaculty Department of Physical Education',
];