scalar Date

enum BookingStatus {
  ACTIVE
  PAST
  CANCELLED
  CANCELLED_LATE
}

type Booking {
  id: ID!
  startDate: Date!
  endDate: Date!
  room: Room!
  user: User!
  status: BookingStatus!
}

type Query {
  allBookings: [Booking!]!
  bookingsByRoom(roomId: ID!): [Booking!]!
  bookingsByDateRange(startDate: Date!, endDate: Date!): [Booking!]!
  bookingsByUser(userId: ID!): [Booking!]!
  bookingsByRoomAndUser(roomId: ID!, userId: ID!, status: BookingStatus): [Booking!]!
  bookingsByRoomAndDate(
    roomId: ID!
    startDate: Date!
    endDate: Date!
  ): [Booking!]!
}

type Mutation {
  createBooking(roomId: ID!, startDate: Date!, endDate: Date!): Booking!

  updateBooking(bookingId: ID!, startDate: Date!, endDate: Date!): Booking

  cancelBooking(bookingId: ID!): UserResponse!

  updatePastBookings: UserResponse!
}
