scalar Date

enum BookingStatus {
  ACTIVE
  PAST
  CANCELLED
  CANCELLED_LATE
}

type Booking {
  id: ID!
  startDate: Date!
  endDate: Date!
  room: Room!
  user: User!
  status: BookingStatus!
  title: String
}

type Query {
  bookings(
    roomId: ID
    userId: ID
    status: BookingStatus
    startDate: Date
    endDate: Date
  ): [Booking!]!
}

type Mutation {
  createBooking(roomId: ID!, startDate: Date!, endDate: Date!, title: String): Booking!

  updateBooking(bookingId: ID!, startDate: Date!, endDate: Date!, title: String): Booking

  cancelBooking(bookingId: ID!): UserResponse!

  updatePastBookings: UserResponse!
}
