enum UserRole {
  ADMIN
  STUDENT
  TEACHER
  MANAGER
}

enum UserStatus {
  ACTIVE
  PENDING
  DISABLED
}

type User {
  id: ID!
  givenName: String!
  middleName: String
  familyName: String!
  username: String!
  email: String!
  role: UserRole!
  status: UserStatus!
  department: Department!
  userNumber: Int!
}

input UserInput {
  givenName: String!
  middleName: String
  familyName: String!
  email: String!
  role: UserRole!
  status: UserStatus!
  departmentId: ID!
}

type Query {
  currentUser: User
}

type UserResponse {
  success: Boolean!
  message: String!
  id: ID
}

type Mutation {
  activateUser(activationToken: String!, newPassword: String!): UserResponse!
  signupRequest(userInput: UserInput!): UserResponse!
}
