// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en' | 'fi' | 'ru';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * C​o​n​f​i​r​m
   */
  CONFIRM: string;
  /**
   * S​e​a​r​c​h
   */
  SEARCH: string;
  /**
   * A​v​a​i​l​a​b​l​e
   */
  AVAILABLE: string;
  /**
   * T​i​m​e
   */
  TIME: string;
  /**
   * B​u​i​l​d​i​n​g
   */
  BUILDING: string;
  /**
   * T​o​o​l​s
   */
  TOOLS: string;
  /**
   * T​y​p​e
   */
  TYPE: string;
  /**
   * R​e​s​e​r​v​e
   */
  RESERVE: string;
  /**
   * O​c​c​u​p​i​e​d
   */
  OCCUPIED: string;
  /**
   * M​y​ ​C​a​l​e​n​d​a​r
   */
  MY_CALENDAR: string;
  /**
   * S​e​t​t​i​n​g​s
   */
  SETTINGS: string;
  /**
   * Y​o​u​ ​h​a​v​e​ ​n​o​ ​u​p​c​o​m​i​n​g​ ​b​o​o​k​i​n​g​s​.
   */
  NO_UPCOMING_BOOKINGS: string;
  /**
   * L​o​g​ ​O​u​t
   */
  LOGOUT: string;
  /**
   * L​o​g​ ​I​n
   */
  LOGIN: string;
  /**
   * B​o​o​k​i​n​g​ ​D​e​t​a​i​l​s
   */
  BOOKING_DETAILS: string;
  /**
   * S​t​a​r​t​s
   */
  STARTS: string;
  /**
   * E​n​d​s
   */
  ENDS: string;
  /**
   * R​o​o​m
   */
  ROOM: string;
  /**
   * T​i​t​l​e
   */
  TITLE: string;
  /**
   * S​h​o​w​ ​U​p​c​o​m​i​n​g​ ​R​e​s​e​r​v​a​t​i​o​n​s
   */
  SHOW_UPCOMING_RESERVATIONS: string;
  /**
   * L​o​a​d​i​n​g​.​.​.
   */
  LOADING: string;
  /**
   * E​R​R​O​R
   */
  ERROR: string;
  /**
   * N​o​t​h​i​n​g​ ​t​o​ ​s​h​o​w​.​.​.
   */
  NOTHING_TO_SHOW: string;
  /**
   * B​o​o​k​i​n​g​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​.
   */
  BOOKING_UPDATED_SUCCESSFULLY: string;
  /**
   * B​o​o​k​i​n​g​ ​t​i​t​l​e
   */
  BOOKING_TITLE: string;
  /**
   * C​a​n​c​e​l​ ​B​o​o​k​i​n​g
   */
  CANCEL_BOOKING_TITLE: string;
  /**
   * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​a​n​c​e​l​ ​t​h​i​s​ ​b​o​o​k​i​n​g​?
   */
  CANCEL_BOOKING_MESSAGE: string;
  /**
   * N​o
   */
  CANCEL_BOOKING_NO: string;
  /**
   * Y​e​s​,​ ​C​a​n​c​e​l
   */
  CANCEL_BOOKING_YES: string;
  /**
   * C​a​n​c​e​l
   */
  CANCEL: string;
  /**
   * M​o​d​i​f​y
   */
  MODIFY: string;
  /**
   * S​e​a​r​c​h​ ​r​o​o​m​s​ ​b​y​ ​c​o​d​e​.​.​.
   */
  SEARCH_ROOMS_BY_CODE: string;
  /**
   * U​s​e​r​n​a​m​e
   */
  USERNAME: string;
  /**
   * P​a​s​s​w​o​r​d
   */
  PASSWORD: string;
  /**
   * G​o​ ​b​a​c​k​ ​t​o​ ​H​o​m​e​ ​s​c​r​e​e​n​!
   */
  GO_BACK_HOME: string;
  /**
   * S​e​a​r​c​h​ ​r​o​o​m​ ​t​y​p​e​s​.​.​.
   */
  SEARCH_ROOM_TYPES: string;
  /**
   * S​t​a​r​t​ ​d​a​t​e​ ​m​u​s​t​ ​b​e​ ​i​n​ ​t​h​e​ ​f​u​t​u​r​e​.
   */
  START_DATE_FUTURE: string;
  /**
   * E​n​d​ ​d​a​t​e​ ​c​a​n​n​o​t​ ​b​e​ ​e​a​r​l​i​e​r​ ​t​h​a​n​ ​s​t​a​r​t​ ​d​a​t​e​.
   */
  END_DATE_BEFORE_START: string;
  /**
   * P​l​e​a​s​e​,​ ​s​e​l​e​c​t​ ​s​t​a​r​t​ ​d​a​t​e​ ​f​i​r​s​t​.
   */
  SELECT_START_DATE: string;
  /**
   * P​l​e​a​s​e​ ​s​e​l​e​c​t​ ​b​o​t​h​ ​s​t​a​r​t​ ​a​n​d​ ​e​n​d​ ​d​a​t​e​s​.
   */
  SELECT_START_AND_END: string;
  /**
   * A​r​e​ ​y​o​u​ ​s​u​r​e​?
   */
  RESET_CONFIRM: string;
  /**
   * T​h​i​s​ ​w​i​l​l​ ​r​e​s​e​t​ ​y​o​u​r​ ​d​a​t​e​ ​s​e​l​e​c​t​i​o​n​s​.
   */
  RESET_WARNING: string;
  /**
   * Y​e​s​,​ ​C​l​e​a​r
   */
  CLEAR: string;
  /**
   * S​e​a​r​c​h​ ​e​q​u​i​p​m​e​n​t​.​.​.
   */
  SEARCH_EQUIPMENT: string;
  /**
   * S​e​a​r​c​h​ ​b​u​i​l​d​i​n​g​ ​b​y​ ​n​a​m​e​.​.​.
   */
  SEARCH_BUILDING: string;
  /**
   * B​o​o​k​i​n​g​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​.
   */
  BOOKING_UPDATED: string;
  /**
   * B​o​o​k​i​n​g​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​.
   */
  BOOKING_CREATED: string;
  /**
   * S​a​v​e
   */
  SAVE: string;
  /**
   * U​s​e​r​n​a​m​e​ ​m​u​s​t​ ​b​e​ ​i​n​ ​t​h​e​ ​f​o​r​m​a​t​ ​'​a​b​1​2​3​4​5​'​.
   */
  USERNAME_FORMAT: string;
  /**
   * P​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d​.
   */
  PASSWORD_REQUIRED: string;
  /**
   * S​e​a​r​c​h
   */
  SEARCH_TAB: string;
  /**
   * C​l​o​s​e
   */
  CLOSE: string;
  /**
   * S​e​l​e​c​t​ ​t​h​e​ ​t​i​m​e​ ​r​a​n​g​e​ ​t​o​ ​s​e​a​r​c​h​ ​f​o​r​ ​a​v​a​i​l​a​b​l​e​ ​c​l​a​s​s​r​o​o​m​s​.
   */
  SELECT_TIME_RANGE: string;
  /**
   * E​m​p​t​y​ ​b​o​o​k​i​n​g
   */
  EMPTY_BOOKINGS: string;
  /**
   * P​l​e​a​s​e​ ​s​e​l​e​c​t​ ​b​o​o​k​i​n​g​ ​t​i​m​e​.
   */
  SELECT_BOOKING_TIME: string;
  /**
   * S​e​l​e​c​t​e​d​ ​l​a​n​g​u​a​g​e​:
   */
  SELECTED_LANGUAGE: string;
  /**
   * S​e​l​e​c​t​ ​l​a​n​g​u​a​g​e
   */
  SELECT_LANGUAGE: string;
};

export type TranslationFunctions = {
  /**
   * Confirm
   */
  CONFIRM: () => LocalizedString;
  /**
   * Search
   */
  SEARCH: () => LocalizedString;
  /**
   * Available
   */
  AVAILABLE: () => LocalizedString;
  /**
   * Time
   */
  TIME: () => LocalizedString;
  /**
   * Building
   */
  BUILDING: () => LocalizedString;
  /**
   * Tools
   */
  TOOLS: () => LocalizedString;
  /**
   * Type
   */
  TYPE: () => LocalizedString;
  /**
   * Reserve
   */
  RESERVE: () => LocalizedString;
  /**
   * Occupied
   */
  OCCUPIED: () => LocalizedString;
  /**
   * My Calendar
   */
  MY_CALENDAR: () => LocalizedString;
  /**
   * Settings
   */
  SETTINGS: () => LocalizedString;
  /**
   * You have no upcoming bookings.
   */
  NO_UPCOMING_BOOKINGS: () => LocalizedString;
  /**
   * Log Out
   */
  LOGOUT: () => LocalizedString;
  /**
   * Log In
   */
  LOGIN: () => LocalizedString;
  /**
   * Booking Details
   */
  BOOKING_DETAILS: () => LocalizedString;
  /**
   * Starts
   */
  STARTS: () => LocalizedString;
  /**
   * Ends
   */
  ENDS: () => LocalizedString;
  /**
   * Room
   */
  ROOM: () => LocalizedString;
  /**
   * Title
   */
  TITLE: () => LocalizedString;
  /**
   * Show Upcoming Reservations
   */
  SHOW_UPCOMING_RESERVATIONS: () => LocalizedString;
  /**
   * Loading...
   */
  LOADING: () => LocalizedString;
  /**
   * ERROR
   */
  ERROR: () => LocalizedString;
  /**
   * Nothing to show...
   */
  NOTHING_TO_SHOW: () => LocalizedString;
  /**
   * Booking updated successfully.
   */
  BOOKING_UPDATED_SUCCESSFULLY: () => LocalizedString;
  /**
   * Booking title
   */
  BOOKING_TITLE: () => LocalizedString;
  /**
   * Cancel Booking
   */
  CANCEL_BOOKING_TITLE: () => LocalizedString;
  /**
   * Are you sure you want to cancel this booking?
   */
  CANCEL_BOOKING_MESSAGE: () => LocalizedString;
  /**
   * No
   */
  CANCEL_BOOKING_NO: () => LocalizedString;
  /**
   * Yes, Cancel
   */
  CANCEL_BOOKING_YES: () => LocalizedString;
  /**
   * Cancel
   */
  CANCEL: () => LocalizedString;
  /**
   * Modify
   */
  MODIFY: () => LocalizedString;
  /**
   * Search rooms by code...
   */
  SEARCH_ROOMS_BY_CODE: () => LocalizedString;
  /**
   * Username
   */
  USERNAME: () => LocalizedString;
  /**
   * Password
   */
  PASSWORD: () => LocalizedString;
  /**
   * Go back to Home screen!
   */
  GO_BACK_HOME: () => LocalizedString;
  /**
   * Search room types...
   */
  SEARCH_ROOM_TYPES: () => LocalizedString;
  /**
   * Start date must be in the future.
   */
  START_DATE_FUTURE: () => LocalizedString;
  /**
   * End date cannot be earlier than start date.
   */
  END_DATE_BEFORE_START: () => LocalizedString;
  /**
   * Please, select start date first.
   */
  SELECT_START_DATE: () => LocalizedString;
  /**
   * Please select both start and end dates.
   */
  SELECT_START_AND_END: () => LocalizedString;
  /**
   * Are you sure?
   */
  RESET_CONFIRM: () => LocalizedString;
  /**
   * This will reset your date selections.
   */
  RESET_WARNING: () => LocalizedString;
  /**
   * Yes, Clear
   */
  CLEAR: () => LocalizedString;
  /**
   * Search equipment...
   */
  SEARCH_EQUIPMENT: () => LocalizedString;
  /**
   * Search building by name...
   */
  SEARCH_BUILDING: () => LocalizedString;
  /**
   * Booking updated successfully.
   */
  BOOKING_UPDATED: () => LocalizedString;
  /**
   * Booking created successfully.
   */
  BOOKING_CREATED: () => LocalizedString;
  /**
   * Save
   */
  SAVE: () => LocalizedString;
  /**
   * Username must be in the format 'ab12345'.
   */
  USERNAME_FORMAT: () => LocalizedString;
  /**
   * Password is required.
   */
  PASSWORD_REQUIRED: () => LocalizedString;
  /**
   * Search
   */
  SEARCH_TAB: () => LocalizedString;
  /**
   * Close
   */
  CLOSE: () => LocalizedString;
  /**
   * Select the time range to search for available classrooms.
   */
  SELECT_TIME_RANGE: () => LocalizedString;
  /**
   * Empty booking
   */
  EMPTY_BOOKINGS: () => LocalizedString;
  /**
   * Please select booking time.
   */
  SELECT_BOOKING_TIME: () => LocalizedString;
  /**
   * Selected language:
   */
  SELECTED_LANGUAGE: () => LocalizedString;
  /**
   * Select language
   */
  SELECT_LANGUAGE: () => LocalizedString;
};

export type Formatters = {};
