scalar Date

enum BookingStatus {
  ACTIVE
  PAST
  CANCELLED
  CANCELLED_LATE
}

type BookingTimeItem {
  value: Date!
  inclusive: Boolean
}

type Booking {
  id: ID!
  bookingTime: [BookingTimeItem!]!
  room: Room!
  user: User!
  status: BookingStatus!
  title: String
}

type Query {
  bookings(
    roomId: ID
    userId: ID
    status: BookingStatus
    startDate: Date
    endDate: Date
  ): [Booking!]!
}

type Mutation {
  createBooking(roomId: ID!, bookingTime: [Date!]!, title: String): Booking!

  updateBooking(
    bookingId: ID!
    bookingTime: [Date!]!
    title: String
    roomId: ID!
  ): Booking!

  cancelBooking(bookingId: ID!): UserResponse!

  updatePastBookings: UserResponse!
}
