name: Deploy to prod

env:
  DEPLOY: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test_and_lint:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format

      - name: Run Jest tests
        run: npm test
        env:
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

  deploy_to_prod:
    needs: [test_and_lint]
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Print folder content
        run: ls -la

      - name: Deploy app
        if: ${{ env.DEPLOY == 'true' }}
        run: flyctl deploy  --dockerfile ./Dockerfile --config ./fly.toml -a winter-water-9193 --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Build Success
        if: ${{ success() && env.DEPLOY == 'true' }}
        run: |
          curl -H "Content-Type: application/json" \
                -X POST \
                -d '{"content": "A new version of Booking app backend deployed to production"}' \
                ${{ secrets.DISCORD_WEBHOOK }}

      - name: Build Fail
        if: ${{ failure() }}
        run: |
          curl -H "Content-Type: application/json" \
                -X POST \
                -d '{"content": "commit https://github.com/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.actor }} broke the build"}' \
              ${{ secrets.DISCORD_WEBHOOK }}
  
  tags_release:
    needs: [deploy_to_prod]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ env.DEPLOY == 'true' }}
        uses: anothrNick/github-tag-action@777684df761b882a3f4f70db16ac70d8cc78d0ea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

        