name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test_and_lint_backend:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (backend)
        working-directory: ./backend
        run: npm ci

      - name: Run ESLint (backend)
        working-directory: ./backend
        run: npm run lint

      - name: Run Prettier (backend)
        working-directory: ./backend
        run: npm run format

      - name: Run Jest tests
        working-directory: ./backend
        run: npm test
        env:
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      

  test_and_lint_frontend:
      needs: [test_and_lint_backend]
      runs-on: ubuntu-20.04

      services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
          ports:
          - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
        
        - name: Install dependencies (backend)
          working-directory: ./backend
          run: npm ci
        
        - name: Build backend
          working-directory: ./backend
          run: npm run build

        - name: Start backend
          working-directory: ./backend
          run: npm run dev
          env:
            DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
        
        - name: Install dependencies (frontend)
          working-directory: ./mobile-frontend
          run: npm ci

        - name: Run ESLint (frontend)
          working-directory: ./mobile-frontend
          run: npm run lint

        - name: Run Prettier (frontend)
          working-directory: ./mobile-frontend
          run: npm run format
        
        - name: Run Jest tests (frontend)
          working-directory: ./mobile-frontend
          run: npm run test

        - name: 🚀 Send build request
          run: eas build --platform all --non-interactive --no-wait --profile development-sim
          shell: bash